application: asper-bot-rates
version: 3-1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /update
  script: update.php

- url: /currency.json
  script: currency.json.php

- url: /.*
  script: index.php

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^(node_modules/.*)
- ^(.git/.*)